package com.db.manager;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.hu.huproject.Entity.AngleEntity;
import com.example.hu.huproject.Entity.HuiShengLunEntity;
import com.example.hu.huproject.Entity.KongDongTimeEntity;
import com.example.hu.huproject.Entity.KongZaiUpEntity;
import com.example.hu.huproject.Entity.ManZaiDownEntity;
import com.example.hu.huproject.Entity.QianYinLiEntity;
import com.example.hu.huproject.Entity.SpeedAngleEntity;
import com.example.hu.huproject.Entity.SpeedEntity;
import com.example.hu.huproject.Entity.TaskEntity;
import com.example.hu.huproject.Entity.ZhiDongLiEntity;

import com.db.manager.AngleEntityDao;
import com.db.manager.HuiShengLunEntityDao;
import com.db.manager.KongDongTimeEntityDao;
import com.db.manager.KongZaiUpEntityDao;
import com.db.manager.ManZaiDownEntityDao;
import com.db.manager.QianYinLiEntityDao;
import com.db.manager.SpeedAngleEntityDao;
import com.db.manager.SpeedEntityDao;
import com.db.manager.TaskEntityDao;
import com.db.manager.ZhiDongLiEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig angleEntityDaoConfig;
    private final DaoConfig huiShengLunEntityDaoConfig;
    private final DaoConfig kongDongTimeEntityDaoConfig;
    private final DaoConfig kongZaiUpEntityDaoConfig;
    private final DaoConfig manZaiDownEntityDaoConfig;
    private final DaoConfig qianYinLiEntityDaoConfig;
    private final DaoConfig speedAngleEntityDaoConfig;
    private final DaoConfig speedEntityDaoConfig;
    private final DaoConfig taskEntityDaoConfig;
    private final DaoConfig zhiDongLiEntityDaoConfig;

    private final AngleEntityDao angleEntityDao;
    private final HuiShengLunEntityDao huiShengLunEntityDao;
    private final KongDongTimeEntityDao kongDongTimeEntityDao;
    private final KongZaiUpEntityDao kongZaiUpEntityDao;
    private final ManZaiDownEntityDao manZaiDownEntityDao;
    private final QianYinLiEntityDao qianYinLiEntityDao;
    private final SpeedAngleEntityDao speedAngleEntityDao;
    private final SpeedEntityDao speedEntityDao;
    private final TaskEntityDao taskEntityDao;
    private final ZhiDongLiEntityDao zhiDongLiEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        angleEntityDaoConfig = daoConfigMap.get(AngleEntityDao.class).clone();
        angleEntityDaoConfig.initIdentityScope(type);

        huiShengLunEntityDaoConfig = daoConfigMap.get(HuiShengLunEntityDao.class).clone();
        huiShengLunEntityDaoConfig.initIdentityScope(type);

        kongDongTimeEntityDaoConfig = daoConfigMap.get(KongDongTimeEntityDao.class).clone();
        kongDongTimeEntityDaoConfig.initIdentityScope(type);

        kongZaiUpEntityDaoConfig = daoConfigMap.get(KongZaiUpEntityDao.class).clone();
        kongZaiUpEntityDaoConfig.initIdentityScope(type);

        manZaiDownEntityDaoConfig = daoConfigMap.get(ManZaiDownEntityDao.class).clone();
        manZaiDownEntityDaoConfig.initIdentityScope(type);

        qianYinLiEntityDaoConfig = daoConfigMap.get(QianYinLiEntityDao.class).clone();
        qianYinLiEntityDaoConfig.initIdentityScope(type);

        speedAngleEntityDaoConfig = daoConfigMap.get(SpeedAngleEntityDao.class).clone();
        speedAngleEntityDaoConfig.initIdentityScope(type);

        speedEntityDaoConfig = daoConfigMap.get(SpeedEntityDao.class).clone();
        speedEntityDaoConfig.initIdentityScope(type);

        taskEntityDaoConfig = daoConfigMap.get(TaskEntityDao.class).clone();
        taskEntityDaoConfig.initIdentityScope(type);

        zhiDongLiEntityDaoConfig = daoConfigMap.get(ZhiDongLiEntityDao.class).clone();
        zhiDongLiEntityDaoConfig.initIdentityScope(type);

        angleEntityDao = new AngleEntityDao(angleEntityDaoConfig, this);
        huiShengLunEntityDao = new HuiShengLunEntityDao(huiShengLunEntityDaoConfig, this);
        kongDongTimeEntityDao = new KongDongTimeEntityDao(kongDongTimeEntityDaoConfig, this);
        kongZaiUpEntityDao = new KongZaiUpEntityDao(kongZaiUpEntityDaoConfig, this);
        manZaiDownEntityDao = new ManZaiDownEntityDao(manZaiDownEntityDaoConfig, this);
        qianYinLiEntityDao = new QianYinLiEntityDao(qianYinLiEntityDaoConfig, this);
        speedAngleEntityDao = new SpeedAngleEntityDao(speedAngleEntityDaoConfig, this);
        speedEntityDao = new SpeedEntityDao(speedEntityDaoConfig, this);
        taskEntityDao = new TaskEntityDao(taskEntityDaoConfig, this);
        zhiDongLiEntityDao = new ZhiDongLiEntityDao(zhiDongLiEntityDaoConfig, this);

        registerDao(AngleEntity.class, angleEntityDao);
        registerDao(HuiShengLunEntity.class, huiShengLunEntityDao);
        registerDao(KongDongTimeEntity.class, kongDongTimeEntityDao);
        registerDao(KongZaiUpEntity.class, kongZaiUpEntityDao);
        registerDao(ManZaiDownEntity.class, manZaiDownEntityDao);
        registerDao(QianYinLiEntity.class, qianYinLiEntityDao);
        registerDao(SpeedAngleEntity.class, speedAngleEntityDao);
        registerDao(SpeedEntity.class, speedEntityDao);
        registerDao(TaskEntity.class, taskEntityDao);
        registerDao(ZhiDongLiEntity.class, zhiDongLiEntityDao);
    }
    
    public void clear() {
        angleEntityDaoConfig.clearIdentityScope();
        huiShengLunEntityDaoConfig.clearIdentityScope();
        kongDongTimeEntityDaoConfig.clearIdentityScope();
        kongZaiUpEntityDaoConfig.clearIdentityScope();
        manZaiDownEntityDaoConfig.clearIdentityScope();
        qianYinLiEntityDaoConfig.clearIdentityScope();
        speedAngleEntityDaoConfig.clearIdentityScope();
        speedEntityDaoConfig.clearIdentityScope();
        taskEntityDaoConfig.clearIdentityScope();
        zhiDongLiEntityDaoConfig.clearIdentityScope();
    }

    public AngleEntityDao getAngleEntityDao() {
        return angleEntityDao;
    }

    public HuiShengLunEntityDao getHuiShengLunEntityDao() {
        return huiShengLunEntityDao;
    }

    public KongDongTimeEntityDao getKongDongTimeEntityDao() {
        return kongDongTimeEntityDao;
    }

    public KongZaiUpEntityDao getKongZaiUpEntityDao() {
        return kongZaiUpEntityDao;
    }

    public ManZaiDownEntityDao getManZaiDownEntityDao() {
        return manZaiDownEntityDao;
    }

    public QianYinLiEntityDao getQianYinLiEntityDao() {
        return qianYinLiEntityDao;
    }

    public SpeedAngleEntityDao getSpeedAngleEntityDao() {
        return speedAngleEntityDao;
    }

    public SpeedEntityDao getSpeedEntityDao() {
        return speedEntityDao;
    }

    public TaskEntityDao getTaskEntityDao() {
        return taskEntityDao;
    }

    public ZhiDongLiEntityDao getZhiDongLiEntityDao() {
        return zhiDongLiEntityDao;
    }

}
