package com.db.manager;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.hu.huproject.Entity.KongDongTimeEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "KONG_DONG_TIME_ENTITY".
*/
public class KongDongTimeEntityDao extends AbstractDao<KongDongTimeEntity, Long> {

    public static final String TABLENAME = "KONG_DONG_TIME_ENTITY";

    /**
     * Properties of entity KongDongTimeEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, long.class, "key", false, "KEY");
        public final static Property MaxSpeed = new Property(2, String.class, "maxSpeed", false, "MAX_SPEED");
        public final static Property CreateTime = new Property(3, String.class, "createTime", false, "CREATE_TIME");
        public final static Property Point_speed = new Property(4, String.class, "point_speed", false, "POINT_SPEED");
        public final static Property RunTimeTotal = new Property(5, String.class, "runTimeTotal", false, "RUN_TIME_TOTAL");
        public final static Property BreakTime1 = new Property(6, String.class, "breakTime1", false, "BREAK_TIME1");
        public final static Property BreakTime2 = new Property(7, String.class, "breakTime2", false, "BREAK_TIME2");
        public final static Property BreakTime = new Property(8, String.class, "breakTime", false, "BREAK_TIME");
        public final static Property TestingNum = new Property(9, Integer.class, "testingNum", false, "TESTING_NUM");
        public final static Property IsSave = new Property(10, boolean.class, "isSave", false, "IS_SAVE");
    }


    public KongDongTimeEntityDao(DaoConfig config) {
        super(config);
    }
    
    public KongDongTimeEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"KONG_DONG_TIME_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"KEY\" INTEGER NOT NULL ," + // 1: key
                "\"MAX_SPEED\" TEXT," + // 2: maxSpeed
                "\"CREATE_TIME\" TEXT," + // 3: createTime
                "\"POINT_SPEED\" TEXT," + // 4: point_speed
                "\"RUN_TIME_TOTAL\" TEXT," + // 5: runTimeTotal
                "\"BREAK_TIME1\" TEXT," + // 6: breakTime1
                "\"BREAK_TIME2\" TEXT," + // 7: breakTime2
                "\"BREAK_TIME\" TEXT," + // 8: breakTime
                "\"TESTING_NUM\" INTEGER," + // 9: testingNum
                "\"IS_SAVE\" INTEGER NOT NULL );"); // 10: isSave
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"KONG_DONG_TIME_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, KongDongTimeEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getKey());
 
        String maxSpeed = entity.getMaxSpeed();
        if (maxSpeed != null) {
            stmt.bindString(3, maxSpeed);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(4, createTime);
        }
 
        String point_speed = entity.getPoint_speed();
        if (point_speed != null) {
            stmt.bindString(5, point_speed);
        }
 
        String runTimeTotal = entity.getRunTimeTotal();
        if (runTimeTotal != null) {
            stmt.bindString(6, runTimeTotal);
        }
 
        String breakTime1 = entity.getBreakTime1();
        if (breakTime1 != null) {
            stmt.bindString(7, breakTime1);
        }
 
        String breakTime2 = entity.getBreakTime2();
        if (breakTime2 != null) {
            stmt.bindString(8, breakTime2);
        }
 
        String breakTime = entity.getBreakTime();
        if (breakTime != null) {
            stmt.bindString(9, breakTime);
        }
 
        Integer testingNum = entity.getTestingNum();
        if (testingNum != null) {
            stmt.bindLong(10, testingNum);
        }
        stmt.bindLong(11, entity.getIsSave() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, KongDongTimeEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getKey());
 
        String maxSpeed = entity.getMaxSpeed();
        if (maxSpeed != null) {
            stmt.bindString(3, maxSpeed);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(4, createTime);
        }
 
        String point_speed = entity.getPoint_speed();
        if (point_speed != null) {
            stmt.bindString(5, point_speed);
        }
 
        String runTimeTotal = entity.getRunTimeTotal();
        if (runTimeTotal != null) {
            stmt.bindString(6, runTimeTotal);
        }
 
        String breakTime1 = entity.getBreakTime1();
        if (breakTime1 != null) {
            stmt.bindString(7, breakTime1);
        }
 
        String breakTime2 = entity.getBreakTime2();
        if (breakTime2 != null) {
            stmt.bindString(8, breakTime2);
        }
 
        String breakTime = entity.getBreakTime();
        if (breakTime != null) {
            stmt.bindString(9, breakTime);
        }
 
        Integer testingNum = entity.getTestingNum();
        if (testingNum != null) {
            stmt.bindLong(10, testingNum);
        }
        stmt.bindLong(11, entity.getIsSave() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public KongDongTimeEntity readEntity(Cursor cursor, int offset) {
        KongDongTimeEntity entity = new KongDongTimeEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // key
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // maxSpeed
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // createTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // point_speed
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // runTimeTotal
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // breakTime1
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // breakTime2
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // breakTime
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // testingNum
            cursor.getShort(offset + 10) != 0 // isSave
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, KongDongTimeEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.getLong(offset + 1));
        entity.setMaxSpeed(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreateTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPoint_speed(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRunTimeTotal(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setBreakTime1(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setBreakTime2(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setBreakTime(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTestingNum(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setIsSave(cursor.getShort(offset + 10) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(KongDongTimeEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(KongDongTimeEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(KongDongTimeEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
