package com.db.manager;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.hu.huproject.Entity.ZhiDongLiEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ZHI_DONG_LI_ENTITY".
*/
public class ZhiDongLiEntityDao extends AbstractDao<ZhiDongLiEntity, Long> {

    public static final String TABLENAME = "ZHI_DONG_LI_ENTITY";

    /**
     * Properties of entity ZhiDongLiEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Key = new Property(1, long.class, "key", false, "KEY");
        public final static Property TestingNum = new Property(2, Integer.class, "testingNum", false, "TESTING_NUM");
        public final static Property MaxZhiDongli = new Property(3, String.class, "maxZhiDongli", false, "MAX_ZHI_DONGLI");
        public final static Property Bizhi = new Property(4, String.class, "bizhi", false, "BIZHI");
        public final static Property ZongZhiDongLi = new Property(5, String.class, "zongZhiDongLi", false, "ZONG_ZHI_DONG_LI");
        public final static Property EdingZhiDongli = new Property(6, String.class, "edingZhiDongli", false, "EDING_ZHI_DONGLI");
        public final static Property Time = new Property(7, String.class, "time", false, "TIME");
        public final static Property IsSave = new Property(8, boolean.class, "isSave", false, "IS_SAVE");
    }


    public ZhiDongLiEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ZhiDongLiEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ZHI_DONG_LI_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"KEY\" INTEGER NOT NULL ," + // 1: key
                "\"TESTING_NUM\" INTEGER," + // 2: testingNum
                "\"MAX_ZHI_DONGLI\" TEXT," + // 3: maxZhiDongli
                "\"BIZHI\" TEXT," + // 4: bizhi
                "\"ZONG_ZHI_DONG_LI\" TEXT," + // 5: zongZhiDongLi
                "\"EDING_ZHI_DONGLI\" TEXT," + // 6: edingZhiDongli
                "\"TIME\" TEXT," + // 7: time
                "\"IS_SAVE\" INTEGER NOT NULL );"); // 8: isSave
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ZHI_DONG_LI_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ZhiDongLiEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getKey());
 
        Integer testingNum = entity.getTestingNum();
        if (testingNum != null) {
            stmt.bindLong(3, testingNum);
        }
 
        String maxZhiDongli = entity.getMaxZhiDongli();
        if (maxZhiDongli != null) {
            stmt.bindString(4, maxZhiDongli);
        }
 
        String bizhi = entity.getBizhi();
        if (bizhi != null) {
            stmt.bindString(5, bizhi);
        }
 
        String zongZhiDongLi = entity.getZongZhiDongLi();
        if (zongZhiDongLi != null) {
            stmt.bindString(6, zongZhiDongLi);
        }
 
        String edingZhiDongli = entity.getEdingZhiDongli();
        if (edingZhiDongli != null) {
            stmt.bindString(7, edingZhiDongli);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(8, time);
        }
        stmt.bindLong(9, entity.getIsSave() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ZhiDongLiEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getKey());
 
        Integer testingNum = entity.getTestingNum();
        if (testingNum != null) {
            stmt.bindLong(3, testingNum);
        }
 
        String maxZhiDongli = entity.getMaxZhiDongli();
        if (maxZhiDongli != null) {
            stmt.bindString(4, maxZhiDongli);
        }
 
        String bizhi = entity.getBizhi();
        if (bizhi != null) {
            stmt.bindString(5, bizhi);
        }
 
        String zongZhiDongLi = entity.getZongZhiDongLi();
        if (zongZhiDongLi != null) {
            stmt.bindString(6, zongZhiDongLi);
        }
 
        String edingZhiDongli = entity.getEdingZhiDongli();
        if (edingZhiDongli != null) {
            stmt.bindString(7, edingZhiDongli);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(8, time);
        }
        stmt.bindLong(9, entity.getIsSave() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ZhiDongLiEntity readEntity(Cursor cursor, int offset) {
        ZhiDongLiEntity entity = new ZhiDongLiEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // key
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // testingNum
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // maxZhiDongli
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bizhi
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // zongZhiDongLi
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // edingZhiDongli
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // time
            cursor.getShort(offset + 8) != 0 // isSave
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ZhiDongLiEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setKey(cursor.getLong(offset + 1));
        entity.setTestingNum(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setMaxZhiDongli(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBizhi(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setZongZhiDongLi(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setEdingZhiDongli(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsSave(cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ZhiDongLiEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ZhiDongLiEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ZhiDongLiEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
